Add a Dockerfile and some instructions
stuck-overflow/ferris-bot pull request #59
Opened 2021-04-11 00:10 UTC by satu

2021-04-11 12:31 UTC, ed-fish approved these changes
:+1

2021-04-11 13:05 UTC, LordMZTE requested changes

2021-04-11 13:05 UTC, LordMZTE commented on Dockerfile
> +    --config-file /etc/ferrisbot.toml
I don't think it's good practive to put this into `/etc`. Instead, i think you should use `/ferrisbot` or `/config`.

2021-04-14 17:36 UTC, satu commented on Dockerfile
> +    --config-file /etc/ferrisbot.toml
done.

2021-04-14 18:00 UTC, LordMZTE approved these changes

2021-04-14 18:00 UTC, merged