Add formatting rules, and change rustfmt toolchain
stuck-overflow/ferris-bot pull request #60
Opened 2021-04-11 04:43 UTC by nyxiative

This closes #38 
formatting rules, has been taken from my work.

2021-04-11 21:40 UTC, satu reviewed
I'd like to limit it for now to very few options, starting from the imports_granularity. I'll try locally and get back to you.

2021-04-11 22:06 UTC, satu requested changes
please revert the changes to the code and re-format. I'd like to keep the git blame history relevant hence we might have to be picky about adding new rustfmt standards.

2021-04-11 22:06 UTC, satu commented on rust-toolchain
> +profile="default"
newline at end of file pls

2021-04-11 22:06 UTC, satu commented on rustfmt.toml
> +imports_granularity="Module"
please keep only this line and remove the rest. we'll iterate over this as we see fit

2021-04-12 19:08 UTC, nyxiative commented
@satu Alright it should be fixed now

2021-04-12 19:13 UTC, satu approved these changes
🥇

2021-04-12 19:14 UTC, merged